services:
  daddykyeta-app:
    container_name: daddykyeta-app
    build: /mnt/user/compose/daddykyeta
    command: node build/main.js
    env_file:
      - /mnt/user/compose/daddykyeta/.env
    volumes:
      - /mnt/user/daddykyeta-data/assets:/app/assets
    depends_on:
      - daddykyeta-db
    restart: unless-stopped

  daddykyeta-db:
    container_name: daddykyeta-db
    image: postgres:latest
    env_file:
      - /mnt/user/compose/daddykyeta/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres_data:
