services:
  app:
    container_name: daddykyeta-app
    build: .
    command: node build/main.js
    env_file:
      - .env
    volumes:
      - ./assets:/app/assets
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: daddykyeta-db
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres_data:
